ARG PHP_VERSION=7.4
FROM php:$PHP_VERSION

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php -r "if (hash_file('sha384', 'composer-setup.php') === file_get_contents('https://composer.github.io/installer.sig')) { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
 && php composer-setup.php \
 && php -r "unlink('composer-setup.php');" \
 && mv composer.phar /usr/local/bin/composer

RUN apt update && apt install -y libzip-dev && docker-php-ext-install zip
RUN pecl install xdebug && docker-php-ext-enable xdebug
