version: '3'

services:

  composer:
    image: composer
    volumes:
      - .:/app
    working_dir: /app

  php:
    build:
      context: docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - .:/app
    working_dir: /app
