version: '3.7'

x-php: &php
  volumes: ['.:/app']
  working_dir: '/app'
  environment:
    XDEBUG_MODE: coverage

services:
  php-7.1: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.1.3, XDEBUG_VERSION: xdebug-2.9.8 } } }
  php-7.2: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.2,   XDEBUG_VERSION: xdebug-3.1.6 } } }
  php-7.3: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.3,   XDEBUG_VERSION: xdebug-3.1.6 } } }
  php-7.4: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.4,   XDEBUG_VERSION: xdebug-3.1.6 } } }
  php-8.0: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 8.0,   XDEBUG_VERSION: xdebug       } } }
  php-8.1: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 8.1,   XDEBUG_VERSION: xdebug       } } }
  php-8.2: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 8.2,   XDEBUG_VERSION: xdebug       } } }
  php-8.3: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 8.3,   XDEBUG_VERSION: xdebug       } } }
