version: '3.7'

x-php: &php
  volumes: ['.:/app']
  working_dir: '/app'
  environment:
    XDEBUG_MODE: coverage

services:
  php-7.1: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.1.3 } } }
  php-7.2: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.2   } } }
  php-7.3: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.3   } } }
  php-7.4: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 7.4   } } }
  php-8.0: { <<: *php, build: { context: docker/php, args: { PHP_VERSION: 8.0   } } }
