version: '3'

services:

  composer:
    image: composer
    volumes: ['.:/app']
    working_dir: '/app'

  php-7.1.3: { image: 'php:7.1.3', volumes: ['.:/app'], working_dir: /app }
  php-7.2:   { image: 'php:7.2',   volumes: ['.:/app'], working_dir: /app }
  php-7.3:   { image: 'php:7.3',   volumes: ['.:/app'], working_dir: /app }
  php-7.4:   { image: 'php:7.4',   volumes: ['.:/app'], working_dir: /app }
