name: Test

on:
  push:
    branches: ['master']
  pull_request: ~

jobs:
  test:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        os: ['ubuntu-latest']
        failure: [false]
        include:
          - { php: 'nightly', os: 'ubuntu-latest', failure: true }
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Install PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php }}'
          tools: 'composer:v2'
          coverage: 'xdebug'
      - name: 'PHP'
        run: 'php -v'

      - name: 'Composer'
        run: 'composer install'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'PHPUnit'
        run: 'php vendor/bin/phpunit --coverage-text'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'Psalm'
        run: 'php vendor/bin/psalm --no-cache --shepherd'
        continue-on-error: '${{ matrix.failure }}'
      - name: 'Infection'
        run: 'php vendor/bin/infection -j2 --min-msi=95'
        continue-on-error: '${{ matrix.failure }}'
